### ISSUE TITLE
Dashboards configurable based on network and hostname

### ISSUE THREAD

**Issue by ilyashatalov** [staking4all/monad-monitoring#2]
Hi! 👋
I’d like to propose a small improvement to the dashboard format, especially for setups where the monitoring stack is not running directly on the validator nodes.

As the number of networks and validators per provider grows in Monad, maintaining a full monitoring stack on each individual node doesn’t seem scalable.

🔧 Proposal:

Let’s make the dashboards configurable based on network and hostname.
(See the example in dashboard v2. attached)

Specifically:
- Add network and hostname labels to each job
- Introduce corresponding variables in the dashboard
- Filter hosts based on the selected network

This way, operating within a single Grafana instance will be easy while switching between validators and networks as needed.
Each validator node would only need to run Prometheus, which sends metrics to a centralised monitoring stack.
Here is how I changed the dash for my purposes
[monad-monitoring-v2.json](https://github.com/user-attachments/files/20780380/monad-monitoring-v2.json)

Of course, we will need to add these labels to targets:
```
  - job_name: node
    scrape_interval: 10s
    static_configs:
      - targets: 
        - "node-exporter:9100"
        labels:
          network: testnet-1
          hostname: monad-devnet-02.staking4all.org
```

Let me know what you think!
